### ISSUE TITLE
Do not try to renew proxy if -proxyfile param is not provided in http_exporter.go 

### ISSUE THREAD

**Issue by mrceyhun** [dmwm/cmsweb-exporters#5]
**Impact of the bug**
http exporter

**Describe the bug**
Even though `-proxyfile` is not provided in these exporters, `http_exporter.go` tries to renew the proxy and produces noisy logs. 
   which are just confusing, but they're working fine and no problem at all.

Some http exporters do not need authentication, so no need proxy; because the endpoints they send request are open to world. Such exporters:
- [http-exporter-dmytro.yaml](https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/monitoring/services/http-exporter-dmytro.yaml)
- [http-exporter-rucio.yaml](https://github.com/dmwm/CMSKubernetes/blob/master/kubernetes/monitoring/services/http-exporter-rucio.yaml)

Here is the example logs:
```
unable to get TLS certificate:  Neither proxy or user certs are found, please setup X509 environment variables
2022/04/21 13:03:34 http_exporter.go:100: user credentials: proxy= cert= ckey=
2022/04/21 13:03:34 http_exporter.go:52: Renew http client, new expire 2022-04-21 13:13:34 +0000 UTC
```

**How to reproduce it**
Just check logs of above exporters in one of cms monitoring cluster

**Additional context and error message**
@vkuznet if you're agree, I can implement it myself such as: if `-proxyfile` parameter is null, do not renew proxy.

fyi @brij01 @leggerf

**Comment by vkuznet** [comment]
@mrceyhun please go ahead with the fix, it's fine by me

**Comment by mrceyhun** [comment]
Done with #6
